GET http://localhost:5000/users

###

GET http://localhost:5000/user/631dc8ee3fbf23253eed9347

###

POST http://localhost:5000/register
Content-Type: application/json

{
  "name": "Fadiah Faradinah",
  "email": "fadiah@gmail.com",
  "password": "12345678"
}

###


POST http://localhost:5000/register
Content-Type: application/json

{
  "name": "Fitriani Nasr",
  "email": "fitriani@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "name": "Fadiah Faradinah",
  "email": "fadiah@gmail.com",
  "password": "999"
}


###

PUT http://localhost:5000/user/631dc8ee3fbf23253eed9347
Content-Type: application/json

{
  "name": "Suryani",
  "email": "fadiah@gmail.com",
  "password": "999"
}

####
DELETE http://localhost:5000/user/631dc8ee3fbf23253eed9347

####
POST http://localhost:5000/delete-users
Content-Type: application/json

["631c9502e4e4eb29817b6731", "631c9502e4e4eb29817b6733"]