GET http://localhost:5000/lanes

###
POST http://localhost:5000/lane
Content-Type: application/json
Accept: application/json

{
  "currentPage": 1,  
  "title": "TO DO",
  "label": "20/70", 
  "cards": [
     {
            "description": "Task1 to do",
            "label": "2017-12-01",
            "title": "Task1"
          },
          {
            "description": "Task2 to do",
            "label": "2017-11-01",
            "title": "Task2"
          },
          {
            "description": "Task3 to do",
            "label": "2017-10-01",
            "title": "Task3"
          },
          {
            "description": "Task4 to do",
            "label": "2017-09-01",
            "title": "Task4"
          }
  ]
}
###
POST http://localhost:5000/lane
Content-Type: application/json
Accept: application/json

{ 
  "title": "TO DO"
}