GET http://localhost:5000/users

###

GET http://localhost:5000/user/63189eaa3eacf9d9276f5722

###

POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Fadiah Faradinah",
  "email": "fadiah@gmail.com",
  "phone_number": "0895611916094"
}

###


POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Fitriani Nasr",
  "email": "fitriani@gmail.com",
  "phone_number": "082347052535"
}

###

PUT http://localhost:5000/user/63189eaa3eacf9d9276f5722
Content-Type: application/json

{
  "name": "Suryani",
  "email": "suryani@gmail.com",
  "phone_number": "0895611916094"
}

####
DELETE http://localhost:5000/user/6318a0e80e9847b9554eeeb5

####
POST http://localhost:5000/delete-users
Content-Type: application/json

["631c9502e4e4eb29817b6731", "631c9502e4e4eb29817b6733"]